port: ":50054"
log_level: "debug"
shutdown_timeout: "10s"
postgres:
  port: "5432"
  host: "postgres"
  db: "chatdb"
  user: "chat"
kafka:
  brokers:
    - "kafka1:9092"
    - "kafka2:9093"
    - "kafka3:9094"
  topic: "messages"
  