FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /message ./cmd/message-service

FROM alpine:latest
WORKDIR /app

COPY --from=builder /message ./message
COPY --from=builder app/config.yaml ./config.yaml

ENTRYPOINT ["/app/message"]

EXPOSE 50054