FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /session ./cmd/session-service

FROM alpine:latest
WORKDIR /app

COPY --from=builder /session ./session
COPY --from=builder app/config.yaml ./config.yaml

ENTRYPOINT ["/app/session"]

EXPOSE 50051