port: ":50053"
log_level: "debug"
shutdown_timeout: "10s"
postgres:
  port: "5432"
  host: "postgres"
  db: "chatdb"
  user: "chat"
  timeout: "5s"
redis:
  addr: "redis:6379"
  db: 0
  ttl: "24h"
kafka:
  brokers:
    - "kafka1:9092"
    - "kafka2:9093"
    - "kafka3:9094"
  topic: "messages"