port: ":50052"
log_level: "debug"
shutdown_timeout: "10s"
postgres:
  port: "5432"
  host: "postgres"
  db: "chatdb"
  user: "chat"
  timeout: "5s"
redis:
  addr: "redis:6379"
  db: 0
  ttl: "24h"
session_addr: "session:50051"