FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY cmd/ cmd/
COPY internal/ internal/

RUN CGO_ENABLED=0 GOOS=linux go build -o /gateway ./cmd/gateway-service

FROM alpine:latest
WORKDIR /app

COPY --from=builder /gateway ./gateway
COPY --from=builder /config/config.yaml ./config.yaml

ENTRYPOINT ["/app/gateway"]

EXPOSE 8080